apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: database
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None