apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-issuer
spec:
  isCA: true
  commonName: ca-issuer
  secretName: ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io