apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: database
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  - port: 9187
    targetPort: 9187
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: database
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None