apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sonarqube
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarqube
      app.kubernetes.io/component: frontend
  podMetricsEndpoints:
  - port: http
    path: /api/monitoring/metrics
    scheme: http
    bearerTokenSecret:
      name: sonarqube-monitoring-passcode
      key: SONAR_WEB_SYSTEMPASSCODE